### ISSUE TITLE
can't checkout repo

### ISSUE THREAD

**Issue by jonwwilkes** [yuq/mesa-lima#1]
When doing a git clone I get the following error:

warning: remote HEAD refers to nonexistent ref, unable to checkout.

**Comment by jermdax** [comment]
If you move into the repository root directory, you can simply checkout the lima-17.1 branch.

See [this link](https://help.github.com/articles/error-remote-head-refers-to-nonexistent-ref-unable-to-checkout/) for more info

**Comment by yuq** [comment]
Sorry, seems the problem of my init push with different branch name. Have fixed it.
